import type { EducationArchetype } from "@/lib/education-systems";

export const COUNTRY_TO_ARCHETYPE: Record<string, EducationArchetype> = {
  PK: "SOUTH_ASIAN",
  BD: "SOUTH_ASIAN",
  LK: "SOUTH_ASIAN",
  NP: "SOUTH_ASIAN",
  IN: "INDIAN",
  GB: "BRITISH",
  AU: "BRITISH",
  NZ: "BRITISH",
  MY: "BRITISH",
  SG: "BRITISH",
  KE: "BRITISH",
  NG: "BRITISH",
  GH: "BRITISH",
  ZA: "BRITISH",
  AE: "BRITISH",
  SA: "BRITISH",
  QA: "BRITISH",
  KW: "BRITISH",
  BH: "BRITISH",
  OM: "BRITISH",
  JO: "BRITISH",
  HK: "BRITISH",
  US: "NORTH_AMERICAN",
  CA: "NORTH_AMERICAN",
  DE: "EUROPEAN_CONTINENTAL",
  FR: "EUROPEAN_CONTINENTAL",
  NL: "EUROPEAN_CONTINENTAL",
  SE: "EUROPEAN_CONTINENTAL",
  NO: "EUROPEAN_CONTINENTAL",
  DK: "EUROPEAN_CONTINENTAL",
  IT: "EUROPEAN_CONTINENTAL",
  ES: "EUROPEAN_CONTINENTAL",
  PL: "EUROPEAN_CONTINENTAL",
  AT: "EUROPEAN_CONTINENTAL",
  BE: "EUROPEAN_CONTINENTAL",
  CH: "EUROPEAN_CONTINENTAL",
  FI: "EUROPEAN_CONTINENTAL",
  PT: "EUROPEAN_CONTINENTAL",
  CZ: "EUROPEAN_CONTINENTAL",
  SK: "EUROPEAN_CONTINENTAL",
  HU: "EUROPEAN_CONTINENTAL",
  RO: "EUROPEAN_CONTINENTAL",
  GR: "EUROPEAN_CONTINENTAL",
  HR: "EUROPEAN_CONTINENTAL",
  RS: "EUROPEAN_CONTINENTAL",
  BG: "EUROPEAN_CONTINENTAL",
  SI: "EUROPEAN_CONTINENTAL",
  EE: "EUROPEAN_CONTINENTAL",
  LV: "EUROPEAN_CONTINENTAL",
  LT: "EUROPEAN_CONTINENTAL",
  TR: "EUROPEAN_CONTINENTAL",
  IR: "EUROPEAN_CONTINENTAL",
  CN: "EAST_ASIAN",
  JP: "EAST_ASIAN",
  KR: "EAST_ASIAN",
  TW: "EAST_ASIAN",
  VN: "EAST_ASIAN",
  TH: "EAST_ASIAN",
  ID: "EAST_ASIAN",
  PH: "EAST_ASIAN",
};

const PRIORITY_CODES = [
  "PK",
  "IN",
  "BD",
  "GB",
  "US",
  "AE",
  "SA",
  "DE",
  "AU",
  "CA",
  "NG",
  "KE",
  "MY",
  "SG",
] as const;

/** ISO 3166-1 alpha-2 → English name */
const COUNTRY_NAMES: Record<string, string> = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AD: "Andorra",
  AO: "Angola",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo (DRC)",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GR: "Greece",
  GD: "Grenada",
  GT: "Guatemala",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macau",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MR: "Mauritania",
  MU: "Mauritius",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  MK: "North Macedonia",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "São Tomé and Príncipe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  KR: "South Korea",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export function countryCodeToEmoji(code: string): string {
  const upper = code.toUpperCase();
  if (upper.length !== 2) return "";
  return String.fromCodePoint(
    ...upper.split("").map((c) => 127397 + c.charCodeAt(0))
  );
}

export function getArchetypeForCountry(countryCode: string): EducationArchetype {
  const code = countryCode.toUpperCase();
  return COUNTRY_TO_ARCHETYPE[code] ?? "GENERIC";
}

export function getCountryName(code: string): string {
  return COUNTRY_NAMES[code.toUpperCase()] ?? code.toUpperCase();
}

/** Resolve stored country (ISO code or legacy full name) to ISO alpha-2 */
export function resolveCountryCode(country: string | null | undefined): string {
  if (!country?.trim()) return "";
  const trimmed = country.trim();
  if (trimmed.length === 2) return trimmed.toUpperCase();
  const byName = Object.entries(COUNTRY_NAMES).find(
    ([, name]) => name.toLowerCase() === trimmed.toLowerCase()
  );
  return byName?.[0] ?? "";
}

export function getCountryOptions(): Array<{
  code: string;
  name: string;
  emoji: string;
}> {
  const allCodes = Object.keys(COUNTRY_NAMES);
  const prioritySet = new Set<string>(PRIORITY_CODES);

  const priority = PRIORITY_CODES.filter((c) => COUNTRY_NAMES[c]).map((code) => ({
    code,
    name: COUNTRY_NAMES[code]!,
    emoji: countryCodeToEmoji(code),
  }));

  const rest = allCodes
    .filter((c) => !prioritySet.has(c))
    .sort((a, b) => COUNTRY_NAMES[a]!.localeCompare(COUNTRY_NAMES[b]!))
    .map((code) => ({
      code,
      name: COUNTRY_NAMES[code]!,
      emoji: countryCodeToEmoji(code),
    }));

  return [...priority, ...rest];
}
