"""initial_schema

Revision ID: ff74b0f69d0e
Revises: 
Create Date: 2026-05-21 16:17:58.254235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.migration_helpers import column_exists, table_exists

# revision identifiers, used by Alembic.
revision: str = 'ff74b0f69d0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _upgrade_fresh_database() -> None:
    """Create all tables on an empty database (local Docker / first install)."""
    import app.models.models  # noqa: F401
    from app.models import Base

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def _upgrade_legacy_database() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Account', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'providerAccountId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Account', 'token_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Account', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Account', 'session_state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('Account_provider_providerAccountId_key'), table_name='Account')
    op.create_unique_constraint(None, 'Account', ['provider', 'providerAccountId'])
    op.drop_constraint(op.f('Account_userId_fkey'), 'Account', type_='foreignkey')
    op.create_foreign_key(None, 'Account', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Conversation', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Conversation', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Conversation', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Conversation', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'New Chat'::text"))
    op.drop_index(op.f('Conversation_userId_idx'), table_name='Conversation')
    op.create_index(op.f('ix_Conversation_userId'), 'Conversation', ['userId'], unique=False)
    op.drop_constraint(op.f('Conversation_userId_fkey'), 'Conversation', type_='foreignkey')
    op.create_foreign_key(None, 'Conversation', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Message', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Message', 'conversationId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('Message_conversationId_idx'), table_name='Message')
    op.create_index(op.f('ix_Message_conversationId'), 'Message', ['conversationId'], unique=False)
    op.drop_constraint(op.f('Message_conversationId_fkey'), 'Message', type_='foreignkey')
    op.create_foreign_key(None, 'Message', 'Conversation', ['conversationId'], ['id'], ondelete='CASCADE')
    op.alter_column('Note', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Note', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Note', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Note', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Note', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False)
    op.alter_column('Note', 'pinnedFrom',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Note', 'fileUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('Note_userId_idx'), table_name='Note')
    op.create_index(op.f('ix_Note_userId'), 'Note', ['userId'], unique=False)
    op.drop_constraint(op.f('Note_userId_fkey'), 'Note', type_='foreignkey')
    op.create_foreign_key(None, 'Note', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('QuizAttempt', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('QuizAttempt', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('QuizAttempt', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('QuizAttempt', 'topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('QuizAttempt', 'difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.drop_index(op.f('QuizAttempt_userId_idx'), table_name='QuizAttempt')
    op.create_index(op.f('ix_QuizAttempt_userId'), 'QuizAttempt', ['userId'], unique=False)
    op.drop_constraint(op.f('QuizAttempt_userId_fkey'), 'QuizAttempt', type_='foreignkey')
    op.create_foreign_key(None, 'QuizAttempt', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Reminder', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Reminder', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Reminder', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Reminder', 'body',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('Reminder_userId_sent_idx'), table_name='Reminder')
    op.create_index(op.f('ix_Reminder_userId'), 'Reminder', ['userId'], unique=False)
    op.create_index('ix_reminder_user_sent', 'Reminder', ['userId', 'sent'], unique=False)
    op.drop_constraint(op.f('Reminder_userId_fkey'), 'Reminder', type_='foreignkey')
    op.create_foreign_key(None, 'Reminder', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Session', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Session', 'sessionToken',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Session', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('Session_sessionToken_key'), table_name='Session')
    op.create_unique_constraint(None, 'Session', ['sessionToken'])
    op.drop_constraint(op.f('Session_userId_fkey'), 'Session', type_='foreignkey')
    op.create_foreign_key(None, 'Session', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('StudyPlan', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('StudyPlan_userId_idx'), table_name='StudyPlan')
    op.create_index(op.f('ix_StudyPlan_userId'), 'StudyPlan', ['userId'], unique=False)
    op.drop_constraint(op.f('StudyPlan_userId_fkey'), 'StudyPlan', type_='foreignkey')
    op.create_foreign_key(None, 'StudyPlan', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('StudySession', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudySession', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudySession', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('StudySession', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('StudySession_userId_idx'), table_name='StudySession')
    op.create_index(op.f('ix_StudySession_userId'), 'StudySession', ['userId'], unique=False)
    op.drop_constraint(op.f('StudySession_userId_fkey'), 'StudySession', type_='foreignkey')
    op.create_foreign_key(None, 'StudySession', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Task', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Task', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Task', 'planId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Task', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('Task_userId_idx'), table_name='Task')
    op.create_index(op.f('ix_Task_userId'), 'Task', ['userId'], unique=False)
    op.drop_constraint(op.f('Task_userId_fkey'), 'Task', type_='foreignkey')
    op.drop_constraint(op.f('Task_planId_fkey'), 'Task', type_='foreignkey')
    op.create_foreign_key(None, 'Task', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Task', 'StudyPlan', ['planId'], ['id'])
    op.alter_column('User', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('User', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('User', 'educationLevel',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.create_unique_constraint(None, 'User', ['email'])
    op.alter_column('VerificationToken', 'identifier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('VerificationToken', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('VerificationToken_identifier_token_key'), table_name='VerificationToken')
    op.drop_index(op.f('VerificationToken_token_key'), table_name='VerificationToken')
    # ### end Alembic commands ###


def upgrade() -> None:
    if not table_exists("Account"):
        _upgrade_fresh_database()
        return

    # Tables already created with the current SQLAlchemy models (fresh Docker install).
    if column_exists("User", "educationArchetypeOverride") or column_exists(
        "User", "hashedPassword"
    ):
        return

    _upgrade_legacy_database()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('VerificationToken_token_key'), 'VerificationToken', ['token'], unique=True)
    op.create_index(op.f('VerificationToken_identifier_token_key'), 'VerificationToken', ['identifier', 'token'], unique=True)
    op.alter_column('VerificationToken', 'token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('VerificationToken', 'identifier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'User', type_='unique')
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.alter_column('User', 'educationLevel',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('User', 'image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.create_foreign_key(op.f('Task_planId_fkey'), 'Task', 'StudyPlan', ['planId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('Task_userId_fkey'), 'Task', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_Task_userId'), table_name='Task')
    op.create_index(op.f('Task_userId_idx'), 'Task', ['userId'], unique=False)
    op.alter_column('Task', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Task', 'planId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Task', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Task', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'StudySession', type_='foreignkey')
    op.create_foreign_key(op.f('StudySession_userId_fkey'), 'StudySession', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_StudySession_userId'), table_name='StudySession')
    op.create_index(op.f('StudySession_userId_idx'), 'StudySession', ['userId'], unique=False)
    op.alter_column('StudySession', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('StudySession', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('StudySession', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('StudySession', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'StudyPlan', type_='foreignkey')
    op.create_foreign_key(op.f('StudyPlan_userId_fkey'), 'StudyPlan', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_StudyPlan_userId'), table_name='StudyPlan')
    op.create_index(op.f('StudyPlan_userId_idx'), 'StudyPlan', ['userId'], unique=False)
    op.alter_column('StudyPlan', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('StudyPlan', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('StudyPlan', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.create_foreign_key(op.f('Session_userId_fkey'), 'Session', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Session', type_='unique')
    op.create_index(op.f('Session_sessionToken_key'), 'Session', ['sessionToken'], unique=True)
    op.alter_column('Session', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Session', 'sessionToken',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Session', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Reminder', type_='foreignkey')
    op.create_foreign_key(op.f('Reminder_userId_fkey'), 'Reminder', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_reminder_user_sent', table_name='Reminder')
    op.drop_index(op.f('ix_Reminder_userId'), table_name='Reminder')
    op.create_index(op.f('Reminder_userId_sent_idx'), 'Reminder', ['userId', 'sent'], unique=False)
    op.alter_column('Reminder', 'body',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Reminder', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Reminder', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Reminder', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'QuizAttempt', type_='foreignkey')
    op.create_foreign_key(op.f('QuizAttempt_userId_fkey'), 'QuizAttempt', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_QuizAttempt_userId'), table_name='QuizAttempt')
    op.create_index(op.f('QuizAttempt_userId_idx'), 'QuizAttempt', ['userId'], unique=False)
    op.alter_column('QuizAttempt', 'difficulty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.alter_column('QuizAttempt', 'topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('QuizAttempt', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('QuizAttempt', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('QuizAttempt', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Note', type_='foreignkey')
    op.create_foreign_key(op.f('Note_userId_fkey'), 'Note', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_Note_userId'), table_name='Note')
    op.create_index(op.f('Note_userId_idx'), 'Note', ['userId'], unique=False)
    op.alter_column('Note', 'fileUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Note', 'pinnedFrom',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Note', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('Note', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Note', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Note', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Note', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.create_foreign_key(op.f('Message_conversationId_fkey'), 'Message', 'Conversation', ['conversationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_Message_conversationId'), table_name='Message')
    op.create_index(op.f('Message_conversationId_idx'), 'Message', ['conversationId'], unique=False)
    op.alter_column('Message', 'conversationId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Message', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Conversation', type_='foreignkey')
    op.create_foreign_key(op.f('Conversation_userId_fkey'), 'Conversation', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_Conversation_userId'), table_name='Conversation')
    op.create_index(op.f('Conversation_userId_idx'), 'Conversation', ['userId'], unique=False)
    op.alter_column('Conversation', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'New Chat'::text"))
    op.alter_column('Conversation', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Conversation', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Conversation', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Account', type_='foreignkey')
    op.create_foreign_key(op.f('Account_userId_fkey'), 'Account', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Account', type_='unique')
    op.create_index(op.f('Account_provider_providerAccountId_key'), 'Account', ['provider', 'providerAccountId'], unique=True)
    op.alter_column('Account', 'session_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Account', 'scope',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Account', 'token_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Account', 'providerAccountId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Account', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
